### ISSUE TITLE
Will not Work, even after making an env

### ISSUE THREAD

**Issue by Dibucci** [GumGum10/QuantumMerge-sdxl#2]
Was shown this by a buddy of mine that does a lot of SDXL model merging and I wanted to give it a go. It did not work for me at all.

at first I could not tell why, all i would get was "Error: Torch not compiled with CUDA enabled"

so i made and put it into an env, then found out a package called "gc" wasn't a thing the the "pip" command could find... so I proceeded to install all the other packages that I could manually and their versions, finally loaded up and the console gave me some actual insight this time... but not good...

was talking about "numpy" compatability issues and i did some digging and downgraded it to 2.0.0 instead of the newer version that was installed... that didn't work... so im at a loss of what to do at this point if im being honest. 

Also, here is the code that the cmd gave me:

```Traceback (most recent call last):  File "G:\Quantom Model Merge\QuantumMerge-sdxl-main\QuantumMerge-sdxl-main\quantumMerge.py", line 1, in <module>
    import torch
  File "G:\Quantom Model Merge\QuantumMerge-sdxl-main\QuantumMerge-sdxl-main\lib\site-packages\torch\__init__.py", line 1382, in <module>
    from .functional import *  # noqa: F403
  File "G:\Quantom Model Merge\QuantumMerge-sdxl-main\QuantumMerge-sdxl-main\lib\site-packages\torch\functional.py", line 7, in <module>
    import torch.nn.functional as F
  File "G:\Quantom Model Merge\QuantumMerge-sdxl-main\QuantumMerge-sdxl-main\lib\site-packages\torch\nn\__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "G:\Quantom Model Merge\QuantumMerge-sdxl-main\QuantumMerge-sdxl-main\lib\site-packages\torch\nn\modules\__init__.py", line 35, in <module>
    from .transformer import TransformerEncoder, TransformerDecoder, \
  File "G:\Quantom Model Merge\QuantumMerge-sdxl-main\QuantumMerge-sdxl-main\lib\site-packages\torch\nn\modules\transformer.py", line 20, in <module>
    device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
G:\Quantom Model Merge\QuantumMerge-sdxl-main\QuantumMerge-sdxl-main\lib\site-packages\torch\nn\modules\transformer.py:20: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
* Running on local URL:  http://127.0.0.1:7860
* To create a public link, set `share=True` in `launch()`.
G:\Quantom Model Merge\QuantumMerge-sdxl-main\QuantumMerge-sdxl-main\lib\site-packages\huggingface_hub\file_download.py:943: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

**Comment by lawrenmurray** [comment]
Getting it to run is actually very simple, and takes about 15 minutes depending on your internet connection.

Step-by-Step: Clone & Run via HTTPS
Assuming you have git installed, navigate to the directory you want to clone it to.

**Comment by lawrenmurray** [comment]
Getting it to run is actually very simple, and takes about 15 minutes depending on your internet connection.

**Step-by-Step: Clone & Run via HTTPS**

Assuming you have git installed, navigate to the directory you want to clone it to and run:
**git clone https://github.com/GumGum10/QuantumMerge-sdxl.git**

Then type or paste:
**cd QuantumMerge-sdxl**

Create a virtual environment:
**python -m venv venv**

Activate it:
**.\venv\Scripts\activate**

Install dependencies:
**pip install torch==2.1.2 transformers==4.38.2 safetensors==0.4.2 tqdm gradio**

From here, I would say you're good to run _python quantumMerge.py_, but I also received the same **error** after running my first **merge**.

_Error: Torch not compiled with CUDA enabled_

(if you have nvidia-smi) In a Command Prompt run:
**nvidia-smi**

In the top right corner you will see your **CUDA** version. I'm running **CUDA 12.9** on an **RTX 4060 Ti**, set up for decent performance, but PyTorch doesn’t yet ship official builds for **CUDA 12.9**. I needed to install PyTorch with **CUDA 12.1**, which is the latest version officially supported by PyTorch and is fully compatible with the **4060 Ti** and driver **576.80**.

If your situation is similar, run this command from the QuantumMerge directory with virtual environment activated:
**pip install torch==2.1.2 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121**

That is the required version for QuantumMerge. Run this command to confirm it worked:
**python -c "import torch; print(torch.cuda.is_available(), torch.version.cuda)"**

You mentioned you were getting _numpy_ errors, and this is likely because your version is _greater_ than **2.X.X.**
In the same virtual environment, run the command:
**pip install "numpy<2"**

Rerun the torch check:
**python -c "import torch; print(torch.cuda.is_available(), torch.version.cuda)"**

After these dependencies are addressed properly you _should_ be able to run _python quantumMerge.py_ and begin merging.

Commands are **copy & paste** ready, _no alterations_ should be made unless needed for **your** computer build.
That's it, really; happy _merging!_
